In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('movie_metadata.csv')

In [3]:
list(df.columns)

['color',
 'director_name',
 'num_critic_for_reviews',
 'duration',
 'director_facebook_likes',
 'actor_3_facebook_likes',
 'actor_2_name',
 'actor_1_facebook_likes',
 'gross',
 'genres',
 'actor_1_name',
 'movie_title',
 'num_voted_users',
 'cast_total_facebook_likes',
 'actor_3_name',
 'facenumber_in_poster',
 'plot_keywords',
 'movie_imdb_link',
 'num_user_for_reviews',
 'language',
 'country',
 'content_rating',
 'budget',
 'title_year',
 'actor_2_facebook_likes',
 'imdb_score',
 'aspect_ratio',
 'movie_facebook_likes']

In [4]:
df.head()

,color,director_name,num_critic_for_reviews,duration,director_facebook_likes,actor_3_facebook_likes,actor_2_name,actor_1_facebook_likes,gross,genres,...,num_user_for_reviews,language,country,content_rating,budget,title_year,actor_2_facebook_likes,imdb_score,aspect_ratio,movie_facebook_likes
0,Color,James Cameron,723.0,178.0,0.0,855.0,Joel David Moore,1000.0,760505847.0,Action|Adventure|Fantasy|Sci-Fi,...,3054.0,English,USA,PG-13,237000000.0,2009.0,936.0,7.9,1.78,33000
1,Color,Gore Verbinski,302.0,169.0,563.0,1000.0,Orlando Bloom,40000.0,309404152.0,Action|Adventure|Fantasy,...,1238.0,English,USA,PG-13,300000000.0,2007.0,5000.0,7.1,2.35,0
2,Color,Sam Mendes,602.0,148.0,0.0,161.0,Rory Kinnear,11000.0,200074175.0,Action|Adventure|Thriller,...,994.0,English,UK,PG-13,245000000.0,2015.0,393.0,6.8,2.35,85000
3,Color,Christopher Nolan,813.0,164.0,22000.0,23000.0,Christian Bale,27000.0,448130642.0,Action|Thriller,...,2701.0,English,USA,PG-13,250000000.0,2012.0,23000.0,8.5,2.35,164000
4,NaN,Doug Walker,NaN,NaN,131.0,NaN,Rob Walker,131.0,NaN,Documentary,...,NaN,NaN,NaN,NaN,NaN,NaN,12.0,7.1,NaN,0

In [5]:
df.movie_title[:20]

0                                               AvatarÂ
1             Pirates of the Caribbean: At World's EndÂ
2                                              SpectreÂ
3                                The Dark Knight RisesÂ
4     Star Wars: Episode VII - The Force AwakensÂ    ...
5                                          John CarterÂ
6                                         Spider-Man 3Â
7                                              TangledÂ
8                              Avengers: Age of UltronÂ
9               Harry Potter and the Half-Blood PrinceÂ
10                  Batman v Superman: Dawn of JusticeÂ
11                                    Superman ReturnsÂ
12                                   Quantum of SolaceÂ
13          Pirates of the Caribbean: Dead Man's ChestÂ
14                                     The Lone RangerÂ
15                                        Man of SteelÂ
16            The Chronicles of Narnia: Prince CaspianÂ
17                                        The AvengersÂ
18         Pirates of the Caribbean: On Stranger TidesÂ
19                                      Men in Black 3Â
Name: movie_title, dtype: object

In [6]:
df.movie_title.nunique()
# 4917 movies

4917

In [7]:
df.movie_title.value_counts()

Victor FrankensteinÂ                               3
King KongÂ                                         3
The Fast and the FuriousÂ                          3
Ben-HurÂ                                           3
PanÂ                                               3
HalloweenÂ                                         3
HomeÂ                                              3
DreddÂ                                             2
HeroÂ                                              2
The CallingÂ                                       2
Halloween IIÂ                                      2
The WatchÂ                                         2
Exodus: Gods and KingsÂ                            2
Alice in WonderlandÂ                               2
Total RecallÂ                                      2
Lucky Number SlevinÂ                               2
Dangerous LiaisonsÂ                                2
Night of the Living DeadÂ                          2
The Full MontyÂ                                    2
Clash of the TitansÂ                               2
The Return of the Living DeadÂ                     2
CrossroadsÂ                                        2
The Twilight Saga: Breaking Dawn - Part 2Â         2
GoosebumpsÂ                                        2
Teenage Mutant Ninja TurtlesÂ                      2
Bad MomsÂ                                          2
TRON: LegacyÂ                                      2
SnatchÂ                                            2
SnitchÂ                                            2
SyrianaÂ                                           2
                                                 ..
ValiantÂ                                           1
MudÂ                                               1
Of Horses and MenÂ                                 1
Beneath Hill 60Â                                   1
You, Me and DupreeÂ                                1
Jerry MaguireÂ                                     1
Super HybridÂ                                      1
Heavenly CreaturesÂ                                1
Life as a HouseÂ                                   1
Drive Me CrazyÂ                                    1
Head Over HeelsÂ                                   1
Albert NobbsÂ                                      1
SelmaÂ                                             1
Last VegasÂ                                        1
The ReapingÂ                                       1
The Best ManÂ                                      1
Mirror MirrorÂ                                     1
Into the BlueÂ                                     1
Dancer in the DarkÂ                                1
PrisonersÂ                                         1
Major DundeeÂ                                      1
A Nightmare on Elm Street 2: Freddy's RevengeÂ     1
The HangoverÂ                                      1
Kindergarten CopÂ                                  1
The Slaughter RuleÂ                                1
Foodfight!Â                                        1
The Tigger MovieÂ                                  1
The HauntingÂ                                      1
The Little PrinceÂ                                 1
The Last LegionÂ                                   1
Name: movie_title, Length: 4917, dtype: int64

In [8]:
df[df['director_name'] == 'James Cameron']

,color,director_name,num_critic_for_reviews,duration,director_facebook_likes,actor_3_facebook_likes,actor_2_name,actor_1_facebook_likes,gross,genres,...,num_user_for_reviews,language,country,content_rating,budget,title_year,actor_2_facebook_likes,imdb_score,aspect_ratio,movie_facebook_likes
0,Color,James Cameron,723.0,178.0,0.0,855.0,Joel David Moore,1000.0,760505847.0,Action|Adventure|Fantasy|Sci-Fi,...,3054.0,English,USA,PG-13,237000000.0,2009.0,936.0,7.9,1.78,33000
26,Color,James Cameron,315.0,194.0,0.0,794.0,Kate Winslet,29000.0,658672302.0,Drama|Romance,...,2528.0,English,USA,PG-13,200000000.0,1997.0,14000.0,7.7,2.35,26000
288,Color,James Cameron,210.0,153.0,0.0,539.0,Jenette Goldstein,780.0,204843350.0,Action|Sci-Fi,...,983.0,English,USA,R,102000000.0,1991.0,604.0,8.5,2.35,13000
291,Color,James Cameron,94.0,141.0,0.0,618.0,Tia Carrere,2000.0,146282411.0,Action|Comedy|Thriller,...,351.0,English,USA,R,115000000.0,1994.0,1000.0,7.2,2.35,0
606,Color,James Cameron,82.0,171.0,0.0,638.0,Todd Graff,2000.0,54222000.0,Adventure|Drama|Sci-Fi|Thriller,...,380.0,English,USA,PG-13,69500000.0,1989.0,650.0,7.6,2.35,0
2486,Color,James Cameron,250.0,154.0,0.0,604.0,Carrie Henn,2000.0,85200000.0,Action|Adventure|Sci-Fi,...,1076.0,English,USA,R,18500000.0,1986.0,626.0,8.4,1.85,18000
3575,Color,James Cameron,204.0,107.0,0.0,255.0,Brian Thompson,2000.0,38400000.0,Action|Sci-Fi,...,692.0,English,UK,R,6500000.0,1984.0,663.0,8.1,1.85,13000

In [11]:
df[df['movie_title'] == 'Avatar']

Empty DataFrame
Columns: [color, director_name, num_critic_for_reviews, duration, director_facebook_likes, actor_3_facebook_likes, actor_2_name, actor_1_facebook_likes, gross, genres, actor_1_name, movie_title, num_voted_users, cast_total_facebook_likes, actor_3_name, facenumber_in_poster, plot_keywords, movie_imdb_link, num_user_for_reviews, language, country, content_rating, budget, title_year, actor_2_facebook_likes, imdb_score, aspect_ratio, movie_facebook_likes]
Index: []

[0 rows x 28 columns]

In [10]:
df.movie_title

0                                                 AvatarÂ
1               Pirates of the Caribbean: At World's EndÂ
2                                                SpectreÂ
3                                  The Dark Knight RisesÂ
4       Star Wars: Episode VII - The Force AwakensÂ    ...
5                                            John CarterÂ
6                                           Spider-Man 3Â
7                                                TangledÂ
8                                Avengers: Age of UltronÂ
9                 Harry Potter and the Half-Blood PrinceÂ
10                    Batman v Superman: Dawn of JusticeÂ
11                                      Superman ReturnsÂ
12                                     Quantum of SolaceÂ
13            Pirates of the Caribbean: Dead Man's ChestÂ
14                                       The Lone RangerÂ
15                                          Man of SteelÂ
16              The Chronicles of Narnia: Prince CaspianÂ
17                                          The AvengersÂ
18           Pirates of the Caribbean: On Stranger TidesÂ
19                                        Men in Black 3Â
20             The Hobbit: The Battle of the Five ArmiesÂ
21                                The Amazing Spider-ManÂ
22                                            Robin HoodÂ
23                   The Hobbit: The Desolation of SmaugÂ
24                                    The Golden CompassÂ
25                                             King KongÂ
26                                               TitanicÂ
27                            Captain America: Civil WarÂ
28                                            BattleshipÂ
29                                        Jurassic WorldÂ
                              ...
5013                                              ManitoÂ
5014                                             RampageÂ
5015                                             SlackerÂ
5016                                         Dutch KillsÂ
5017                                           Dry SpellÂ
5018                                            FlywheelÂ
5019                                              ExeterÂ
5020                                          The RidgesÂ
5021                                     The Puffy ChairÂ
5022                                Stories of Our LivesÂ
5023                                    Breaking UpwardsÂ
5024                            All Superheroes Must DieÂ
5025                                      Pink FlamingosÂ
5026                                               CleanÂ
5027                                          The CircleÂ
5028                                         Tin Can ManÂ
5029                                            The CureÂ
5030                                      On the DownlowÂ
5031                        Sanctuary; Quite a ConundrumÂ
5032                                                BangÂ
5033                                              PrimerÂ
5034                                              CaviteÂ
5035                                         El MariachiÂ
5036                                     The Mongol KingÂ
5037                                           NewlywedsÂ
5038                             Signed Sealed DeliveredÂ
5039                           The FollowingÂ
5040                                A Plague So PleasantÂ
5041                                    Shanghai CallingÂ
5042                                   My Date with DrewÂ
Name: movie_title, Length: 5043, dtype: object

In [ ]:
ironman_list =